name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-analyze-deploy:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - name: Checkout c칩digo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Instalar dependencias con Yarn
        run: yarn install --frozen-lockfile

      - name: Ejecutar pruebas con cobertura
        run: yarn test --coverage

      - name: Verificar existencia del archivo lcov
        run: test -f coverage/lcov.info

      - name: Ejecutar linter
        run: yarn lint

      - name: An치lisis de seguridad (yarn audit)
        run: yarn audit --level moderate || true

      - name: An치lisis est치tico con SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.TOKEN_APP }}
        run: |
          yarn global add sonarqube-scanner
          sonar-scanner \
            -Dsonar.projectKey=kamivillabla_realestate-api \
            -Dsonar.organization=kamivillabla \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.login=$SONAR_TOKEN

      - name: Despliegue a entorno de staging
        env:
          TOKEN_APP: ${{ secrets.TOKEN_APP }}
        run: |
          echo "Desplegando a entorno de pruebas (staging)..."
          curl -X POST https://api.transchile.cl/staging-deploy \
            -H "Authorization: Bearer $TOKEN_APP" \
            -H "Content-Type: application/json" \
            -d '{"version": "latest", "env": "staging"}'
